### ISSUE TITLE
Questbook Suggestion

### ISSUE THREAD

**Issue by Dream-Master** [Drethic/QuestBook#10]
This is a suggesion from a user using my Modpack.

"Every time when you open a book, it opens not on the last page you were on, but the front page. Because sometimes you open a book 10-20 times per quest, this thing becomes very annoying.

Also right now you are unable to view the recipe of an item that quest requires. Right clicking on it doesn't open NEI and this was very convenient."

GTNewHorizons/NewHorizons#635

**Comment by Drethic** [comment]
Which version of Better Questing and Questbook are you using so I can try to reproduce locally?  Also I read in your issue thread you couldn't reproduce the issue your self, is this a server or local pack?  If it's a server are you an Op and if so what level.  Trying to figure out where some of the differences may be since the Questbook code essentially calls the same code as pressing ~.

Can you have any users who can reproduce it try using the keyboard shortcut to see if they go back to the quest or if goes to the root page.  This will help narrow down if it's Questbook or Better Questing.

**Comment by Dream-Master** [comment]
Yes i am Server admin (SSH, FTP, Console) and we using Better Questing 1.0.141 and Questbook 1.1.0.
https://github.com/GTNewHorizons/NewHorizons

Will test it in Sp and Mp and report what i find out.

**Comment by Dream-Master** [comment]
SP works for me have to ask my Players if works in MP too. Sorry for the Delay.

**Comment by Dream-Master** [comment]
@Drethic Yea on MP it switch back to Main site. (Sp works fine so far i test it) Is this a Quest Book issue or a Better qusting Mod issue.

**Comment by Drethic** [comment]
With the latest updates of 1.2.0/2.0.0 for 1.7.10 both issues brought up in this thread should now be fixed.  If not please let me know and I'll do what I can to address them and work with @Funwayguy.  I'd recommend going to the 2.x version of Better Questing for the new API for better bookmark support for the repeat opening issue mentioned above.
