### ISSUE TITLE
[Question] How to change the home image?

### ISSUE THREAD

**Issue by Zack7292** [Drethic/QuestBook#34]
Hi, i've been trying to change my home image for about 3h now, but even tho i've watched videos, the wiki, etc... i don't seem to understand how to set up the file path, could somebody please explain me how to do this, bcs it's a bit annoying. 

![image](https://user-images.githubusercontent.com/45187146/79370163-33070300-7f20-11ea-848a-fc806f96af12.png)

btw, i've needed to create the files by myself since they didn't automatically generate and the way to set the path in the general config isn't there. i'm with the latest build of it.

**Comment by Drethic** [comment]
That setting is from the main mod BetterQuesting, from my understanding you have to create a square image that is at least 512 x 512 where the top half (512 x 256) is the background for the home page.  If you have further issues getting this in place you may need to open a ticket on the BetterQuesting GitHub [here](https://github.com/Funwayguy/BetterQuesting).  Please be sure to provide which version of Minecraft and the exact version of BetterQuesting you are using so that Funwayguy will know which steps to provide you.  He's been working on new versions across different Minecraft versions that `latest` is not always a good indicator.

**Comment by Zack7292** [comment]
just realised i was on the wrong github lol , thx tho, ima try when i got time

**Comment by Zack7292** [comment]
just open the thing
