### ISSUE TITLE
Quest boonot workng in enigmatica 2 expert

### ISSUE THREAD

**Issue by teenymario123** [Drethic/QuestBook#35]
Im having an issue where the quest book doesnt let me complete quests for ex a checkbox task requires me to press a button in the book and when I do nothing happens (no arrows on the side of detect/submit).

**Comment by teenymario123** [comment]
/bq_admin complete (quest-id) doesnt complete the quest id that I give it.

**Comment by Drethic** [comment]
Sounds like there is an issue with your installation of Enigmatica 2 which is causing Better Questing to have an issue.  Unfortunately I have no experience with that pack and cannot be much assistance troubleshooting your issue.  You will want to reach out to them directly.  From the curse forge page I see they have a Discord and that would be your best bet.

As for the `/bq_admin` command not working there are a few possible reasons.  Only certain commands work on a server and you must be an Op with rank 4 to use them.  Otherwise you have to be in a local game to adjust things.  If it does not work in single player you may have to reach out to FunwayGuy to see if there is something not set properly for the main mod.  Unfortunately I just make the book addon and have limited insight into how the core works.
